##SIFAT-SIFAT DETERMINANT



1.   Pertukaran kolom dengan kolom tidak mempengaruhi determinan.
2.   Pertukaran dua baris manapun akan mengubah tanda,tetapi nilai determinannya tidak berubah.
1.  Perkalian dari satu baris manapun dengan skalar x akan mengubah nilai determinan sebesar x kali.







In [3]:
import numpy as np
A = np. array (([1,0],[0,1]))
B = np.array(([1,0,0],[0,1,0],[0,0,1]))
C = np.array(([1,2,1],[3,1,2],[2,1,2]))
D = np.array(([1,2,1],[1,2,1],[2,1,2]))
E = np.array (([1,2,1],[2,4,2],[2,1,2]))
F = np.array (([1,2,1],[2,4,2],[2,4,3]))
G = np.array (([6,2,4],[2,4,2],[4,2,3]))
H = np.array (([6,8],[4,2]))
I = np.array (([6,8],[2,1]))
J = np.array (([6,4],[4,1]))


det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)
det_D = np.linalg.det(D)
det_E = np.linalg.det(E)
det_F = np.linalg.det(F)
det_G = np.linalg.det(G)
det_H = np.linalg.det(H)
det_I = np.linalg.det(I)
det_J = np.linalg.det(J)


print(det_A)
print(det_B)
print(det_C)
print(det_D)
print(det_E)
print(det_F)
print(det_G)
print(det_H)
print(det_I)
print(det_J)

1.0
1.0
-3.000000000000001
0.0
0.0
0.0
4.000000000000005
-19.999999999999996
-9.999999999999998
-9.999999999999998


In [4]:
import numpy as np

n = 3

upper_matrix = np.triu(np.ones((n, n)), k=0)
print("Matriks segitiga atas:")
print(upper_matrix)

lower_matrix = np.tril(np.ones((n, n)), k=0)
print("\nMatriks segitiga bawah:")
print(lower_matrix)

determinant_upper = np.linalg.det(upper_matrix)
print("\nDeterminan matriks segitiga atas:", determinant_upper)

determinant_lower = np.linalg.det(lower_matrix)
print("Determinan matriks segitiga bawah:", determinant_lower)

Matriks segitiga atas:
[[1. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]

Matriks segitiga bawah:
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]

Determinan matriks segitiga atas: 1.0
Determinan matriks segitiga bawah: 1.0
