##SIFAT-SIFAT DETERMINANT



1.  Jika baris Matrix Identitas ditukar maka akan mengubah tanda dari Determinan Matrix Identitas tersebut

2.  Jika di dalam suatu Matrix ada baris atau yang merupakan kelipatan dari baris atau kolom yang lain maka det = 0.

3.  Jika ada Matrix kelipatan dari matrix lain maka determinan matrix tersebut adalah kelipatan pangkat ordo kali determinan matrix dari kelipatannya.

4.  Jika Determinan Matrix B adalah 2x Determinan Matrix A maka ada salah satu baris Matrix B yang menjadi 2x lipat baris Matrix A.

5.  Jika ada matrix yang berasal dari penjumlahan matrix A dan matrix B maka determinannya adalah penjumlahan dari matrix A dan Matrix B.

6.  Jika ada Matrix segitiga atas maka determinannya adalah perkalian anggota diagonal Matrix tersebut.






In [1]:
import numpy as np

A = np.array([[1,0],[0,1]])
B = np.array([[1,0,0],[0,1,0],[0,0,1]])
C = np.array([[1,0,0],[0,0,1],[0,1,0]])
D = np.array([[0,1,0],[0,0,1],[1,0,0]])
E = np.array([[1,2,1],[3,1,2],[2,1,2]])
F = np.array([[3,1,2],[1,2,1],[2,1,2]])
G = np.array([[1,2,1],[2,4,2],[2,1,2]])
H = np.array([[1,2,2],[2,4,4],[1,2,3]])
I = np.array([[6,2,4],[2,4,2],[4,2,4]])
J = np.array([[3,4],[2,1]])
K = np.array([[6,8],[4,2]])
L = np.array([[2*3,2*4],[2,1]])
M = np.array([[2*3,4],[2*2,1]])
N = np.array([[4,1],[2,1]])
O = np.array([[7,5],[2,1]])
P = np.array([[2,3,2],[0,2,2],[0,0,2]])
Q = np.array([[2,1],[1,1]])
R = np.array([[1,1],[1,1]])
S = np.array([[3,3],[2,2]])


print(f"Matrix A (Identitas)=\n{A}")
print(f"Matrix B (Identitas)=\n{B}")
print(f"Matrix C =\n{C}")
print(f"Matrix D =\n{D}")
print(f"Matrix E =\n{E}")
print(f"Matrix F =\n{F}")
print(f"Matrix G =\n{G}")
print(f"Matrix H =\n{H}")
print(f"Matrix I =\n{I}")
print(f"Matrix J =\n{J}")
print(f"Matrix K =\n{K}")
print(f"Matrix L =\n{L}")
print(f"Matrix M =\n{M}")
print(f"Matrix N =\n{N}")
print(f"Matrix O =\n{O}")
print(f"Matrix P =\n{P}")
print(f"Matrix Q =\n{Q}")
print(f"Matrix R =\n{R}")
print(f"Matrix S =\n{S}")

det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)
det_D = np.linalg.det(D)
det_E = np.linalg.det(E)
det_F = np.linalg.det(F)
det_G = np.linalg.det(G)
det_H = np.linalg.det(H)
det_I = np.linalg.det(I)
det_J = np.linalg.det(J)
det_K = np.linalg.det(K)
det_L = np.linalg.det(L)
det_M = np.linalg.det(M)
det_N = np.linalg.det(N)
det_O = np.linalg.det(O)
det_P = np.linalg.det(P)
det_Q = np.linalg.det(Q)
det_R = np.linalg.det(R)
det_S = np.linalg.det(S)

print("")
print(f"Determinan Matrix A =\n{det_A}")
print("")
print(f"Determinan Matrix B =\n{det_B}")
print("")
print(f"Determinan Matrix C =\n{det_C}")
print("")
print(f"Determinan Matrix D =\n{det_D}")
print("")
print(f"Determinan Matrix E =\n{det_E}")
print("")
print(f"Determinan Matrix F =\n{det_F}")
print("")
print(f"Determinan Matrix G =\n{det_G}")
print("")
print(f"Determinan Matrix H =\n{det_H}")
print("")
print(f"Determinan Matrix I =\n{det_I}")
print("")
print(f"Determinan Matrix J =\n{det_J}")
print("")
print(f"Determinan Matrix K =\n{det_K}")
print("")
print(f"Determinan Matrix L =\n{det_L}")
print("")
print(f"Determinan Matrix M =\n{det_M}")
print("")
print(f"Determinan Matrix N =\n{det_N}")
print("")
print(f"Determinan Matrix O =\n{det_O}")
print("")
print(f"Determinan Matrix P =\n{det_P}")
print("")
print(f"Determinan Matrix Q =\n{det_Q}")
print("")
print(f"Determinan Matrix R =\n{det_R}")
print("")
print(f"Determinan Matrix S =\n{det_S}")

Matrix A (Identitas)=
[[1 0]
 [0 1]]
Matrix B (Identitas)=
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Matrix C =
[[1 0 0]
 [0 0 1]
 [0 1 0]]
Matrix D =
[[0 1 0]
 [0 0 1]
 [1 0 0]]
Matrix E =
[[1 2 1]
 [3 1 2]
 [2 1 2]]
Matrix F =
[[3 1 2]
 [1 2 1]
 [2 1 2]]
Matrix G =
[[1 2 1]
 [2 4 2]
 [2 1 2]]
Matrix H =
[[1 2 2]
 [2 4 4]
 [1 2 3]]
Matrix I =
[[6 2 4]
 [2 4 2]
 [4 2 4]]
Matrix J =
[[3 4]
 [2 1]]
Matrix K =
[[6 8]
 [4 2]]
Matrix L =
[[6 8]
 [2 1]]
Matrix M =
[[6 4]
 [4 1]]
Matrix N =
[[4 1]
 [2 1]]
Matrix O =
[[7 5]
 [2 1]]
Matrix P =
[[2 3 2]
 [0 2 2]
 [0 0 2]]
Matrix Q =
[[2 1]
 [1 1]]
Matrix R =
[[1 1]
 [1 1]]
Matrix S =
[[3 3]
 [2 2]]

Determinan Matrix A =
1.0

Determinan Matrix B =
1.0

Determinan Matrix C =
-1.0

Determinan Matrix D =
1.0

Determinan Matrix E =
-3.000000000000001

Determinan Matrix F =
3.000000000000001

Determinan Matrix G =
0.0

Determinan Matrix H =
0.0

Determinan Matrix I =
24.000000000000014

Determinan Matrix J =
-5.000000000000001

Determinan Matrix K =
-19.9999999999

In [2]:
import numpy as np

a = np.array([[3,4],[2,1,]])
b = np.array([[1,0,0],[0,1,0],[0,0,1]])
c = np.array([[1,2,1],[3,1,2],[2,1,2]])
d = np.array([[3,1,2],[1,2,1],[2,1,2]])
e = np.array([[1,2,1],[2,4,2],[2,1,2]])
f = np.array([[1,2,1],[2,4,2],[2,4,3]])
g = np.array([[6,2,4],[2,4,2],[4,2,4]])
h = np.array([[6,8],[4,2]])
i = np.array([[6,8],[2,1]])
j = np.array([[6,4],[4,1]])
k = np.array([[4,1],[2,1]])
l = np.array([[7,5],[2,1]])
upper = np.array([[1,2,3],[0,1,2,],[0,0,1]])
lower = np.array([[1,0,0],[1,2,0],[1,2,3]])
aaa = np.array([[2,1],[1,1]])
bbb = np.array([[1,1],[1,1]])
ccc =  aaa@bbb


### 1. Jika terdapat Matriks Identitas maka Determinannya adalah 1 berapapun ordonya




In [3]:
print("Matriks A :")
print(b)

det = np.linalg.det(b)
print(f"Determinan dari Matriks A : {int(det.round())}")

Matriks A :
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Determinan dari Matriks A : 1


### 2. Jika salah satu baris diubah nilai elemennya maka hasil determinannnya juga ikut berubah

In [4]:
print("Matriks B :")
print(c)
det = np.linalg.det(c)
print(f"Determinan dari Matriks B : {int(det.round())}")


print("\n")
print("Matriks C :")
print(d)
detc = np.linalg.det(d)
print(f"Determinan dari Matriks C : {int(detc.round())}")

Matriks B :
[[1 2 1]
 [3 1 2]
 [2 1 2]]
Determinan dari Matriks B : -3


Matriks C :
[[3 1 2]
 [1 2 1]
 [2 1 2]]
Determinan dari Matriks C : 3


### 3.  Jika suatu baris ataupun kolom merupakan kelipatan dari baris atau kolom yang lain maka determinan matrix tersebut adalah 0 (baris 2 adalah kelipatan dari baris 1)

In [5]:
print("Matriks D :")
print(e)
det = np.linalg.det(e)
print(f"Determinan dari Matriks D : {int(det.round())}")


print("\n")
print("Matriks E :")
print(f)
detc = np.linalg.det(f)
print(f"Determinan dari Matriks E : {int(detc.round())}")

Matriks D :
[[1 2 1]
 [2 4 2]
 [2 1 2]]
Determinan dari Matriks D : 0


Matriks E :
[[1 2 1]
 [2 4 2]
 [2 4 3]]
Determinan dari Matriks E : 0


### 4. Jika matrix tersebut adalah kelipatan sebanyak n * matrix maka untuk mencari determinan adalah (n^(sebanyak ordo)determinan matrix)contoh matrix g adalah kelipatan 2 kali dari matrix d

In [6]:
print("Matriks D :")
print(d)
det = np.linalg.det(d)
print(f"Determinan dari Matriks D : {int(det.round())}")


print("\n")
print("Matriks G :")
print(g)
detc = np.linalg.det(g)
print(f"Determinan dari Matriks G : {int(detc.round())}")

Matriks D :
[[3 1 2]
 [1 2 1]
 [2 1 2]]
Determinan dari Matriks D : 3


Matriks G :
[[6 2 4]
 [2 4 2]
 [4 2 4]]
Determinan dari Matriks G : 24



$$
Simulasi : 2^3(3) = 6*3 = 24
$$


In [7]:
print("Matriks A :")
print(a)
det = np.linalg.det(a)
print(f"Determinan dari Matriks A : {int(det.round())}")


print("\n")
print("Matriks G :")
print(h)
detc = np.linalg.det(h)
print(f"Determinan dari Matriks H : {int(detc.round())}")


Matriks A :
[[3 4]
 [2 1]]
Determinan dari Matriks A : -5


Matriks G :
[[6 8]
 [4 2]]
Determinan dari Matriks H : -20



$$
Simulasi : 2^2(-5) = 4*(-5) = -20
$$


### 5. Jika terdapat matrix baru dengan nilai salah satu baris atau kolom adalah kelipatan 2 dari matrix sebelumnya maka dapat disimpulkan dengan 2*(determinan matrix)

*   contoh matrix i baris pertama adalah kelipatan 2 dari matrix a
*   contoh matrix j kolom pertama adalah kelipatan 2 dari matrix a


In [8]:
print("Matriks A :")
print(a)
det = np.linalg.det(a)
print(f"Determinan dari Matriks A : {int(det.round())}")


print("\n")
print("Matriks I :")
print(i)
det1 = np.linalg.det(i)
print(f"Determinan dari Matriks I : {int(det1.round())}")
print("Matriks J :")
print(j)
detc = np.linalg.det(j)
print(f"Determinan dari Matriks I : {int(detc.round())}")


Matriks A :
[[3 4]
 [2 1]]
Determinan dari Matriks A : -5


Matriks I :
[[6 8]
 [2 1]]
Determinan dari Matriks I : -10
Matriks J :
[[6 4]
 [4 1]]
Determinan dari Matriks I : -10


### 6. Jika suatu matrix yang berasal dari penjumlahan matrix k dengan matrix a maka untuk mencari determinan cukup menjumlahkan hasil dari 2 determinan matrix tersebut

In [9]:
print("Matriks K :")
print(k)
det = np.linalg.det(k)
print(f"Determinan dari Matriks k : {int(det.round())}")
print("   +")
print("Matriks L :")
print(l)
det1 = np.linalg.det(l)
print(f"Determinan dari Matriks L : {int(det1.round())}")
print("Hasill  : ")
print("Matriks A :")
print(a)
detc = np.linalg.det(a)
print(f"Determinan dari Matriks A : {int(detc.round())}")


Matriks K :
[[4 1]
 [2 1]]
Determinan dari Matriks k : 2
   +
Matriks L :
[[7 5]
 [2 1]]
Determinan dari Matriks L : -3
Hasill  : 
Matriks A :
[[3 4]
 [2 1]]
Determinan dari Matriks A : -5


### 7. Jika ada matrix segitiga atas atau bawah maka determinan nya adalah perkalian anggota diagonal matrix tersebut

In [10]:
print("Matriks Setiga atas :")
print(upper)
det = np.linalg.det(upper)
print(f"Determinan dari Matriks Setiga Atas : {int(det.round())}")


print("\n")
print("Matriks Setiga Bawah :")
print(lower)
det1 = np.linalg.det(lower)
print(f"Determinan dari Matriks Setiga Bawah : {int(det1.round())}")


Matriks Setiga atas :
[[1 2 3]
 [0 1 2]
 [0 0 1]]
Determinan dari Matriks Setiga Atas : 1


Matriks Setiga Bawah :
[[1 0 0]
 [1 2 0]
 [1 2 3]]
Determinan dari Matriks Setiga Bawah : 6


### 8. untuk mencari determinan dari Hasil perkalian matrix O dengan matrix p yaitu dengan mengalikan determinan matrix O dan p contoh (det O = 1 , det p = 1 maka det q adalah 0)

In [11]:
print("Matriks AAA :")
print(aaa)
det = np.linalg.det(aaa)
print(f"Determinan dari Matriks BBB : {int(det.round())}")
print("   x")
print("Matriks BBB :")
print(bbb)
det1 = np.linalg.det(bbb)
print(f"Determinan dari Matriks BBB : {int(det1.round())}")
print("Hasill  : ")
print("Matriks CCC :")
print(ccc)
detc = np.linalg.det(ccc)
print(f"Determinan dari Matriks CCC : {int(detc.round())}")


Matriks AAA :
[[2 1]
 [1 1]]
Determinan dari Matriks BBB : 1
   x
Matriks BBB :
[[1 1]
 [1 1]]
Determinan dari Matriks BBB : 0
Hasill  : 
Matriks CCC :
[[3 3]
 [2 2]]
Determinan dari Matriks CCC : 0


# Cofactor


### Tugas Kofaktor matrix ordo 5x5
Matrix yang akan saya buat adalah matrix dengan ordo 5x5

ialah sebagai berikut
$$
A=\begin{bmatrix}
1 &2&1&1&1\\
2&1&3&1&1\\
3&2&3&2&2 \\
4&1&1&4&3\\
3&5&1&2&2
\end{bmatrix}
$$
Matrix ini akan saya jadikan invers, hal pertama yang akan cari adalah determinannya terlebih dahulu

Rumus Kofaktor=
$$
C_{ij} = (-1)^{i+j} * detA
$$

rumus det (pick one row or column) =
$$
a_{ij} * c_{ij} + a_{ij} * c_{ij} + a_{ij} * c_{ij} + a_{nn} * c_{nn}$$

rumus invers matrix =
$${ \frac{1}{detA}} * adj(a)$$

Mencari Adjoin =
$$adj(A) = (kof(A))^T$$

(adj(S) = Transpose dari setiap cofator-cofator Matrix)

In [12]:
import numpy as np

matrix_A = np.array([[1,2,1,1,1],[2,1,3,1,1],[3,2,3,2,2],[4,1,1,4,3],[3,5,1,2,2]])
print(f"Matrix A: \n{matrix_A}")
det_Mat_A = np.linalg.det(matrix_A)
inv_Mat_A = np.linalg.inv(matrix_A)
print(f"pembuktian Determinan= {det_Mat_A}")
print(f"pembuktian Invers = \n{inv_Mat_A.round(1)}")
print()
print("="*50)
# kita mencari determinannya terlebih dahulu dengan Pick setiap row

A11 = np.array([[1,3,1,1],[2,3,2,2],[1,1,4,3],[5,1,2,2]])
A12 = np.array([[2,3,1,1],[3,3,2,2],[4,1,4,3],[3,1,2,2]])
A13 = np.array([[2,1,1,1],[3,2,2,2],[4,1,4,3],[3,5,2,2]])
A14 = np.array([[2,1,3,1],[3,2,3,2],[4,1,1,3],[3,5,1,2]])
A15 = np.array([[2,1,3,1],[3,2,3,2],[4,1,1,4],[3,5,1,2]])
A21 = np.array([[2,1,1,1],[2,3,2,2],[1,1,4,3],[5,1,2,2]])
A22 = np.array([[1,1,1,1],[3,3,2,2],[4,1,4,3],[3,1,2,2]])
A23 = np.array([[1,2,1,1],[3,2,2,2],[4,1,4,3],[3,5,2,2]])
A24 = np.array([[1,2,1,1],[3,2,3,2],[4,1,1,3],[3,5,1,2]])
A25 = np.array([[1,2,1,1],[3,2,3,2],[4,1,1,4],[3,5,1,2]])
A31 = np.array([[2,1,1,1],[1,3,1,1],[1,1,4,3],[1,1,2,2]])
A32 = np.array([[1,1,1,1],[2,3,1,1],[4,1,4,3],[3,1,2,2]])
A33 = np.array([[1,2,1,1],[2,1,1,1],[4,1,4,3],[3,1,2,2]])
A34 = np.array([[1,2,1,1],[2,1,3,1],[4,1,1,3],[3,1,1,2]])
A35 = np.array([[1,2,1,1],[2,1,3,1],[4,1,1,4],[3,1,1,2]])
A41 = np.array([[2,1,1,1],[1,3,1,1],[2,3,2,2],[5,1,2,2]])
A42 = np.array([[1,1,1,1],[2,3,1,1],[3,3,2,2],[3,1,2,2]])
A43 = np.array([[1,2,1,1],[2,1,1,1],[3,2,2,2],[3,5,2,2]])
A44 = np.array([[1,2,1,1],[2,1,3,1],[3,2,3,2],[3,5,1,2]])
A45 = np.array([[1,2,1,1],[2,1,3,1],[3,2,3,2],[3,5,1,2]])
A51 = np.array([[2,1,1,1],[1,3,1,1],[2,3,2,2],[1,1,4,3]])
A52 = np.array([[1,1,1,1],[2,3,1,1],[3,3,2,2],[4,1,4,3]])
A53 = np.array([[1,2,1,1],[2,1,1,1],[3,2,2,2],[4,1,4,3]])
A54 = np.array([[1,2,1,1],[2,1,3,1],[3,2,3,2],[4,1,1,3]])
A55 = np.array([[1,2,1,1],[2,1,3,1],[3,2,3,2],[4,1,1,4]])

det_11 = np.linalg.det(A11)
det_12 = np.linalg.det(A12)
det_13 = np.linalg.det(A13)
det_14 = np.linalg.det(A14)
det_15 = np.linalg.det(A15)
det_21 = np.linalg.det(A21)
det_22 = np.linalg.det(A22)
det_23 = np.linalg.det(A23)
det_24 = np.linalg.det(A24)
det_25 = np.linalg.det(A25)
det_31 = np.linalg.det(A31)
det_32 = np.linalg.det(A32)
det_33 = np.linalg.det(A33)
det_34 = np.linalg.det(A34)
det_35 = np.linalg.det(A35)
det_41 = np.linalg.det(A41)
det_42 = np.linalg.det(A42)
det_43 = np.linalg.det(A43)
det_44 = np.linalg.det(A44)
det_45 = np.linalg.det(A45)
det_51 = np.linalg.det(A51)
det_52 = np.linalg.det(A52)
det_53 = np.linalg.det(A53)
det_54 = np.linalg.det(A54)
det_55 = np.linalg.det(A55)

c11 = (-1)**(1+1) * det_11
c12 = (-1)**(1+2) * det_12
c13 = (-1)**(1+3) * det_13
c14 = (-1)**(1+4) * det_14
c15 = (-1)**(1+5) * det_15
c21 = (-1)**(2+1) * det_21
c22 = (-1)**(2+2) * det_22
c23 = (-1)**(2+3) * det_23
c24 = (-1)**(2+4) * det_24
c25 = (-1)**(2+5) * det_25
c31 = (-1)**(3+1) * det_31
c32 = (-1)**(3+2) * det_32
c33 = (-1)**(3+3) * det_33
c34 = (-1)**(3+4) * det_34
c35 = (-1)**(3+5) * det_35
c41 = (-1)**(4+1) * det_41
c42 = (-1)**(4+2) * det_42
c43 = (-1)**(4+3) * det_43
c44 = (-1)**(4+4) * det_44
c45 = (-1)**(4+5) * det_45
c51 = (-1)**(5+1) * det_51
c52 = (-1)**(5+2) * det_52
c53 = (-1)**(5+3) * det_53
c54 = (-1)**(5+4) * det_54
c55 = (-1)**(5+5) * det_55

a11 = matrix_A[0][0]
a12 = matrix_A[0][1]
a13 = matrix_A[0][2]
a14 = matrix_A[0][3]
a15 = matrix_A[0][4]
a21 = matrix_A[1][0]
a22 = matrix_A[1][1]
a23 = matrix_A[1][2]
a24 = matrix_A[1][3]
a25 = matrix_A[1][4]
a31 = matrix_A[2][0]
a32 = matrix_A[2][1]
a33 = matrix_A[2][2]
a34 = matrix_A[2][3]
a35 = matrix_A[2][4]
a41 = matrix_A[3][0]
a42 = matrix_A[3][1]
a43 = matrix_A[3][2]
a44 = matrix_A[3][3]
a45 = matrix_A[3][4]
a51 = matrix_A[4][0]
a52 = matrix_A[4][1]
a53 = matrix_A[4][2]
a54 = matrix_A[4][3]
a55 = matrix_A[4][4]

# Row 1
det_A_row1 = a11*c11 + a12*c12 + a13*c13 + a14*c14 + a15*c15
print(f"det A = {det_A_row1}")
# Row 2
det_A_row2 = a21*c21 + a22*c22 + a23*c23 + a24*c24 + a25*c25
print(f"det A = {det_A_row2}")
# Row 3
det_A_row3 = a31*c31 + a32*c32 + a33*c33 + a34*c34 + a35*c35
print(f"det A = {det_A_row3}")
# Row 4
det_A_row4 = a41*c41 + a42*c42 + a43*c43 + a44*c44 + a45*c45
print(f"det A = {det_A_row4}")
# Row 5
det_A_row5 = a51*c51 + a52*c52 + a53*c53 + a54*c54 + a55*c55
print(f"det A = {det_A_row5}")
Kof_Matrix_A = np.array([[c11,c12,c13,c14,c15],[c21,c22,c23,c24,c25],[c31,c32,c33,c34,c35],[c41,c42,c43,c44,c45],[c51,c52,c53,c54,c55]])
print(f"\nMarix dengan anggota kofaktor-kofaktornya = \n{Kof_Matrix_A}")
Trans_Kof_Matrix_A = Kof_Matrix_A.transpose()
print(f"\nTranspose Matrix dari kofaktornya = \n{Trans_Kof_Matrix_A}")
invers_A = 1 / det_A_row1 * Trans_Kof_Matrix_A
print(f"\nHasil Invers Matrix adalah = \n{invers_A.round(1)}")
print(f"\n Kita bandingkan dengan matriks asal : \n {inv_Mat_A.round(1)}")

Matrix A: 
[[1 2 1 1 1]
 [2 1 3 1 1]
 [3 2 3 2 2]
 [4 1 1 4 3]
 [3 5 1 2 2]]
pembuktian Determinan= -5.000000000000011
pembuktian Invers = 
[[-1.8  0.2  0.2 -0.   0.6]
 [ 0.4  0.4 -0.6 -0.   0.2]
 [ 0.6  0.6 -0.4 -0.  -0.2]
 [ 2.   3.  -4.   1.  -0. ]
 [-0.6 -4.6  5.4 -1.  -0.8]]

det A = -5.000000000000031
det A = -4.9999999999999964
det A = -1.0
det A = -5.0
det A = -4.999999999999998

Marix dengan anggota kofaktor-kofaktornya = 
[[ 9.00000000e+00 -2.00000000e+00 -3.00000000e+00 -1.00000000e+01
   3.00000000e+00]
 [-1.00000000e+00 -2.00000000e+00 -3.00000000e+00 -1.50000000e+01
   2.30000000e+01]
 [ 7.00000000e+00  3.00000000e+00 -2.00000000e+00  4.00000000e+00
  -1.50000000e+01]
 [-0.00000000e+00  0.00000000e+00 -0.00000000e+00 -5.00000000e+00
   5.00000000e+00]
 [-3.00000000e+00 -1.00000000e+00  1.00000000e+00  3.55271368e-15
   4.00000000e+00]]

Transpose Matrix dari kofaktornya = 
[[ 9.00000000e+00 -1.00000000e+00  7.00000000e+00 -0.00000000e+00
  -3.00000000e+00]
 [-2.00000000e+